### ISSUE TITLE
What was motivation for creating a fork?

### ISSUE THREAD

**Issue by munrocket** [FlorisSteenkamp/double-double#9]
Looks like this library inspired by my [double.js](https://github.com/munrocket/double.js)? Because no one used one-square and inlined fast-two-sum directly in code. What was motivation? Actually I am proud of my unique library in js even if it not so popular, but you get a catchy name and somehow appear in searching engines better. I think you should include my library in references/benchmark.

**Comment by FlorisSteenkamp** [comment]
Hi munrocket

No, my library was not inspired by your library. I needed double-double
precision
*with error bounds* for some of my other libraries. The *with error bounds*
part
here is crucial.

I did see your library at some point while doing my research but all my
functions
are from the research papers I followed.
If I recall correctly, I *did* find the research of "J.-M. Muller" from
your library.
I also got the *square root of a double-double* code from you (that I
included
for completeness) plus I have put a link to your library at the top of the
function
(since the beginning).

The difference between our versions is:
  * My library don't use any classes, your's does
  * Mine don't use objects to represent double-double's, it uses arrays
  * Mine include error bounds, your's don't
  * Many more

I have experimented with WASM but gave up after realizing the calls into
WASM
from JS were too slow.

I also experienced with inlining stuff but if I recall correctly never got
any performance
improvements.

When I get time I will include a reference to your library plus benchmarks
as you've asked.

Kind regards

Floris

**Comment by munrocket** [comment]
> When I get time I will include a reference to your library plus benchmarks

Thanks I will appreciate it.

> objects to represent double-double's, it uses arrays

Yes, because according to my benchmark objects are faster for small arrays (seems they become records js engines)

> My library don't use any classes, your's does

I am curious how better it is without classes/prototypes. I just found that my library already was fastest and the main bottleneck is lack of fma operation. So if you interested in speed please leave comment in proposal in javascript for additional fma operation https://es.discourse.group/t/math-float-optimisation/829
You can explain there your usecase and why it is important. 

> Mine include error bounds

This is probably most significant difference, because I saw nearly all libraries on this topic and tried to leave a library small and simple. Before someone’s request.

Lot of people don’t need additional precision, but who need it deciding to create a fork instead of collaborating. Cringe. Another guy done pretty much the same. I never seen the same in python/rust.
